placeholders:
    oro_activity_list_before:
        items:
            orocrm_activity_contact: ~

items:
    orocrm_activity_contact:
        action: OroCRMActivityContactBundle:ActivityContact:metrics
