parameters:
#    oro_activiy_contact.listener.activity_contact_migration.class: OroCRM\Bundle\ActivityContactBundle\EventListener\ActivityContactMigrationListener
    oro_activity_contact.entity_config_dumper.extension.class:     OroCRM\Bundle\ActivityContactBundle\Tools\ActivityContactConfigDumperExtension

services:
#    oro_activiy_contact.listener.activity_contact_migration:
#        class: %oro_activiy_contact.listener.activity_contact_migration.class%
#        arguments:
#            - @oro_entity_extend.migration.entity_metadata_helper
#        tags:
#            - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp, priority: 0 }

    oro_activity_contact.entity_config_dumper.extension:
        class: %oro_activity_contact.entity_config_dumper.extension.class%
        arguments:
            - @oro_entity_config.config_manager
            - @oro_entity_extend.extend.field_type_helper
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }
