parameters:
    orocrm_activiy_contact.listener.activity_contact_migration.class: OroCRM\Bundle\ActivityContactBundle\EventListener\ActivityContactMigrationListener
    orocrm_activity_contact.entity_config_dumper.extension.class:     OroCRM\Bundle\ActivityContactBundle\Tools\ActivityContactConfigDumperExtension

services:
    orocrm_activiy_contact.listener.activity_contact_migration:
        class: %orocrm_activiy_contact.listener.activity_contact_migration.class%
        arguments:
            - @oro_entity_extend.migration.entity_metadata_helper
        tags:
            - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp }

    orocrm_activity_contact.entity_config_dumper.extension:
        class: %orocrm_activity_contact.entity_config_dumper.extension.class%
        arguments:
            - @oro_entity_config.config_manager
            - @oro_entity_extend.extend.field_type_helper
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }
